<?php
$collection = $this->getCollection();
$countPerRow = $this->getCountPerRow();
$numberRow = $this->getNumberRow();
$urlKey = $this->getUrlKey();
$helper = $this->helper('mpanel');
$col = $this->getCountPerRow();
$col = $helper->convertColRowCustom($col);
?>

<div class="featured-brands">
	<div class="content-heading">
		<?php if ($this->getTitle() != ''): ?>
			<h3 class="title"><?php echo $this->getTitle(); ?></h3>
		<?php endif ?>
		<?php if ($this->getSubTitle() != ''): ?>
			<div class="block-note"><?php echo $this->getSubTitle(); ?></div>
		<?php endif ?>
	</div>
	<div class="brand-block brand-grid-block">
	<?php if (count($collection)): ?>
		<div class="block widget mgs-brand">
			
			<?php if($this->getSlider()==1): ?>
				<div class="row">
					<?php $_collectionSize = count($collection) ?>
					<div class="brands-grid owl-carousel owl-theme owl-carousel-init" id="owl-brands">
						<?php $_columnCount = 1; ?>
						
						<?php if($this->getNumberRow()!=''): ?>
							<?php $_columnCount = $this->getNumberRow() * $this->getCountPerRow(); ?>
						<?php endif ?>
						
						<?php $i=0; foreach ($collection as $brand): ?>
							
							<?php if($this->getNumberRow()>1): ?>
								<?php if ($i++%$_columnCount==0): ?>
									<div class="items">
								<?php endif ?>
										<div class="col-md-<?php echo $col; ?> col-sm-4 col-xs-6 margin-bottom30<?php if($i % 3 == 1): ?> first-sm-item<?php endif ?><?php if($i % 2 == 1): ?> first-sm-item<?php endif ?>">
							<?php endif ?>
							
											<div class="brand-items">
												<div class="image">
													<a class="photo" title="<?php echo $brand->getTitle(); ?>" href="<?php echo $this->getUrl() . $urlKey . '/' . $brand->getUrlKey(); ?>">
														<?php if ($brand->getIcon() != ''): ?>
															<img class="img-responsive" alt="<?php echo $brand->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/' . $brand->getIcon(); ?>">
														<?php else: ?>
															<img class="img-responsive" alt="<?php echo $brand->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/mgs/brand/no_image.png'; ?>">
														<?php endif; ?>
													</a>
												</div>
											</div>
									
							<?php if($this->getNumberRow()>1): ?>
										</div>
								<?php if ($i%$_columnCount==0 || $i==$_collectionSize): ?>
									</div>
								<?php endif ?>
							<?php endif ?>
							
						 <?php endforeach ?>
					</div>
					<script type="text/javascript">
						mgsjQuery("#owl-brands").owlCarousel({
							<?php if ($this->getNumberRow() == 1): ?>
							items : <?php echo $this->getCountPerRow(); ?>,
							<?php else: ?>
							singleItem: true,
							<?php endif ?>
							lazyLoad : false,
							navigation : <?php echo $this->getNavigation() ?>,
							pagination : <?php echo $this->getPagination() ?>,
							autoPlay: <?php echo $this->getAutoPlay() ?>,
							stopOnHover: <?php echo $this->getStopHover() ?>,
							navigationText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
							<?php if($this->getNumberRow() == 1): ?>
							itemsDesktop: [1199,<?php echo $this->getCountPerRow(); ?>],
							itemsDesktopSmall: [991,4],
							itemsTabletSmall: [767,3],
							itemsMobile: [499,2],
							itemsCustom: false
							<?php endif ?>
						});
					</script>
				</div>
			<?php else: ?>
				<ul class="brands-grid widget mgs-brand row">
					<?php $i = 0; foreach ($collection as $brand): $i++; ?>
						<li class="<?php if($col !=''): ?>col-md-<?php echo $col; ?> col-sm-4 col-xs-6 margin-bottom30<?php endif; ?><?php if($i % 3 == 1): ?> first-sm-item<?php endif ?><?php if($i % 2 == 1): ?> first-sm-item<?php endif ?>">
						
							<div class="brand-items">
								<div class="image">
									<a class="photo" title="<?php echo $brand->getTitle(); ?>" href="<?php echo $this->getUrl() . $urlKey . '/' . $brand->getUrlKey(); ?>">
										<?php if ($brand->getIcon() != ''): ?>
											<img class="img-responsive" alt="<?php echo $brand->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/' . $brand->getIcon(); ?>">
										<?php else: ?>
											<img class="img-responsive" alt="<?php echo $brand->getTitle(); ?>" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/mgs/brand/no_image.png'; ?>">
										<?php endif; ?>
									</a>
								</div>
							</div>
						</li>
					<?php endforeach ?>
				</ul>
			<?php endif ?>
		</div>
	<?php else: ?>
		<div class="alert alert-danger">
			<p><?php echo $this->__('There are no brands matching the selection.') ?></p>
		</div>
	<?php endif ?>
</div>
</div>