<?php
	/* * ****************************************************
		* Package   : Brand
		* Author    : HIEPNH
		* Copyright : (c) 2015
	* ***************************************************** */
?>
<?php $product_url_not_rw = Mage::getBaseUrl() . 'catalog/product/view/id/'; ?>
<?php
	$panelHelper = $this->helper('mpanel');
	$_productCollection = $this->getLoadedProductCollection();
	$_helper = $this->helper('catalog/output');
	$model = $this->getBrand();
	$helper = Mage::helper('brand');
?>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if ($model->getImage() != ''): ?>
<div class="category-image text-center">
	<img class="img-responsive" width="<?php echo $imageWidth; ?>" height="<?php echo $imageHeight; ?>"
	title="<?php echo $model->getTitle(); ?>" alt="<?php echo $model->getTitle(); ?>"
	src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB) . 'media/' . $model->getImage(); ?>">
</div>
<?php endif; ?>

<?php if ($model->getDescription() != ''): ?>
<div class="brand-description std">
	<p><?php echo $model->getDescription(); ?></p>
</div>
<?php endif; ?>

<?php if (!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products row">
	<div class="col-md-12">
		<?php echo $this->getToolbarBlock()->setTemplate('catalog/product/list/top_toolbar.phtml')->toHtml(); ?>
	</div>
	<?php // List mode ?>
	<?php if ($this->getMode() != 'grid'): ?>
	<?php $_iterator = 0; ?>
	<ol class="products-list" id="products-list">
		<?php foreach ($_productCollection as $_product): ?>
		<li class="col-md-12 item<?php if (++$_iterator == sizeof($_productCollection)): ?> last<?php endif; ?>">
			<div class="row">
				<?php // Product Image ?>
				<div class="col-md-3 col-sm-4 col-xs-12">
					<div class="product-top">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
						<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-small"/>
						<?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('small_image'))): ?>
							<img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-hover"/>
						<?php endif;?>
					</a>
						<?php echo $panelHelper->getProductLabel($_product) ?>
						<button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $product_url_not_rw . $_product->getId() ?>'); return false;"><em class="pe-7s-search"></em></button>
					</div>
					
				</div>
				<?php // Product description ?>
				<div class="col-md-9 col-sm-8 col-xs-12">
					<div class="product-desc">
						<?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
						<h5 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a></h5>
						<?php echo $this->getReviewsSummaryHtml($_product, false, true) ?>
						<?php echo $this->getPriceHtml($_product, true) ?>
						<div class="desc std">
							<p><?php echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?></p>                                       
						</div>
						<div class="controls">
							<div class="add-to-cart">
								<?php if ($_product->isSaleable()): ?>
									<?php if ($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()): ?>
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-primary" onclick="setLocation('<?php echo $product_url_not_rw . $_product->getId() ?>')"><?php echo $this->__('Add to Cart') ?></button>
									<?php else: ?>
										<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart btn-primary" onclick="setLocation('<?php echo $product_url_not_rw . $_product->getId() ?>')"><?php echo $this->__('Add to Cart') ?></button>
									<?php endif; ?>
								<?php else: ?>
									<p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
								<?php endif; ?>
							</div>
							<ul class="icon-links">                                           
										<?php if ($this->helper('wishlist')->isAllow() && !Mage::getStoreConfig('mpanel/catalog/wishlist_button')) : ?>
									<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="window.location.href = '<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>'" class="btn-addto"><em class="pe-7s-like"></em></button></li>
								<?php endif; ?>
								<?php $_compareUrl = $this->getAddToCompareUrl($_product);
									//var_dump($_compareUrl);
								?>
								<?php if ( $_compareUrl && !Mage::getStoreConfig('mpanel/catalog/compare_button')): ?>
									<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')" class="btn-addto"><em class="pe-7s-graph3"></em></button></li>
								<?php endif; ?>
							</ul>
						</div>
					</div>
				   
				</div>
			</div>
		</li>
		<?php endforeach; ?>
	</ol>
	<script type="text/javascript">decorateList('products-list', 'none-recursive')</script>
	
	<?php else: ?>
	
	<?php // Grid Mode ?>
	<?php $_collectionSize = $_productCollection->count() ?>

	<?php $col = $panelHelper->getCol() ?>
	<?php $perrow = $panelHelper->getPerrow(); ?>
	<?php $itemClass = $panelHelper->getColClass($perrow) ?>
	<?php $_collectionSize = $_productCollection->count() ?>
	<?php $_columnCount = $this->getColumnCount(); ?>
	
	<?php
		$i = 0;
		foreach ($_productCollection as $_product):
	?>
	<?php if ($i++ % $_columnCount == 0): ?>
	<ul class="products-grid">
		<?php endif ?>
		<li class="item <?php echo $itemClass?> <?php echo $panelHelper->getClearClass($perrow, $i);?>">
			<div class="product-item-info metro_template <?php if(Mage::getStoreConfig('mpanel/catalog/disable_hover_effect') == 1): ?> <?php echo "disable_hover_effect" ?><?php endif ?>">
				<div class="product-content">
						<div class="product-top">
							<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
								<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-small"/>
								<?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('small_image'))): ?>
									<img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-hover"/>
								<?php endif;?>
							</a>
							<?php echo $panelHelper->getProductLabel($_product) ?>
							<ul class="icon-links">
								<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
									<li class="li-quickview hidden-sm hidden-xs">
										<button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $product_url_not_rw . $_product->getId() ?>'); return false;"><em class="pe-7s-search"></em></button></li>
								<?php endif ?>
								<?php if ($this->helper('wishlist')->isAllow() && $panelHelper->isShowWishList()) : ?>
									<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="pe-7s-like"></em></button></li>
								<?php endif; ?>
								<?php $_compareUrl = $this->getAddToCompareUrl($_product);
											
										?>
								<?php if($_compareUrl && $panelHelper->isShowCompare()): ?>
									<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="pe-7s-graph3"></em></button></li>
								<?php endif; ?>
							</ul>
							<?php if($panelHelper->isShowAddtoCart()): ?>
								<div class="add-to-cart">
									<?php if ($_product->isSaleable()): ?>
										<?php if ($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()): ?>
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart" onclick="setLocation('<?php echo $product_url_not_rw . $_product->getId() ?>')"><span><?php echo $this->__('Add to Cart'); ?></span></button>
										<?php else: ?>
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart'); ?></span></button>
										<?php endif; ?>
									<?php else: ?>
										<p><?php echo $this->__('Our of stock') ?></p>
									<?php endif; ?>
								</div>
							<?php endif ?>
						</div>
						<div class="product-desc">
							<h5 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h5>
							<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
							
							<?php if($panelHelper->isShowAddtoCart()): ?>
								<div class="add-to-cart hover_effect">
									<?php if ($_product->isSaleable()): ?>
										<?php if ($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped()): ?>
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart" onclick="setLocation('<?php echo $product_url_not_rw . $_product->getId() ?>')"><span><?php echo $this->__('Add to Cart'); ?></span></button>
										<?php else: ?>
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart'); ?></span></button>
										<?php endif; ?>
									<?php else: ?>
										<p><?php echo $this->__('Our of stock') ?></p>
									<?php endif; ?>
								</div>
							<?php endif ?>
						</div>
					</div>
			</div>
		</li>
		<?php if ($i % $_columnCount == 0 || $i == $_collectionSize): ?>
	</ul>
	<?php endif ?>
	<?php endforeach ?>
	<script type="text/javascript">decorateGeneric($$('ul.products-grid'), ['odd', 'even', 'first', 'last'])</script>
	<?php endif; ?>
</div>
<?php endif; ?>