<?php if($this->getTitle() != '' || $this->getSubTitle() != ''): ?>
	<div class="content-heading">
		<?php if($this->getTitle() != ''): ?>
			<h3 class="title"><?php echo $this->getTitle(); ?></h3>
		<?php endif ?>
		<?php if($this->getSubTitle() != ''): ?>
			<div class="block-note"><?php echo $this->getSubTitle(); ?></div>
		<?php endif ?>
	</div>
<?php endif ?>

<?php if(Mage::getStoreConfig('deals/general/enabled')): ?>
	<?php $_productCollection=$this->getProductCollection(); ?>
	<?php $_helper = $this->helper('catalog/output'); ?>
	<?php $helper = $this->helper('mpanel'); ?>
	<?php $widgetId = $this->getWidgetId(); ?>
	<?php $useSlider = $this->getUseSlider(); ?>
	
	<?php $useBootstrap = false; ?>
	<?php if(!$useSlider){
		$useBootstrap = true;
	}else {
		if($this->getNumberRow() > 1){
			$useBootstrap = true;
		}
	}
	?>
	
	<?php $size = $helper->convertRatioToSize($this->getProductRatio()) ?>

	<?php if(count($_productCollection)>0): ?>
		<?php $_columnCount = $this->getColumn(); ?>
		<?php if($useSlider && $this->getNumberRow() == 1): ?>
		<div class="row">
		<?php endif ?>
		<div id="deals-product-grid" class="products-grid deal-products-grid<?php if($useSlider): ?> owl-carousel<?php if($this->getNumberRow() == 1): ?> slider-1-row<?php endif ?><?php endif ?><?php if(!$useSlider): ?> row<?php endif ?>">
			<?php $i = 0; foreach ($_productCollection as $product): $i++; ?>
				<?php $_product = Mage::getModel('catalog/product')->load($product->getId()) ?>
				<?php if($useSlider && $this->getNumberRow() > 1): ?>
					<?php $countPerSlider = $_columnCount * $this->getNumberRow(); ?>
					<?php if($i % $countPerSlider == 1): ?>
						<div class="multiple-row-item row">
					<?php endif ?>
				<?php endif ?>
							<div class="item<?php if($useBootstrap): ?> col-lg-<?php echo $helper->convertColRow($_columnCount) ?> col-md-<?php echo $helper->convertColRow($_columnCount) ?> col-xs-12<?php endif ?>">
								<div class="product-item-info product_metro <?php if(Mage::getStoreConfig('mpanel/catalog/disable_hover_effect') == 1): ?> <?php echo "disable_hover_effect" ?><?php endif ?>">
									<div class="product-top">
										<a href="<?php echo $_product->getProductUrl() ?>" title="" class="product-image photo" >
											<img class="img-responsive product-image-photo" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']); ?>" alt="<?php echo $this->htmlEscape($this->getImageLabel($_product, 'small_image'), null, true) ?>" />
											<?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('small_image'))): ?>
												<img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-hover"/>
											<?php endif;?>
										</a>
										<?php $save = $_product->getPrice() - $_product->getFinalPrice() ?>
										<?php $percent = round(($save*100)/$_product->getPrice(), 1) ?>
										<span class="product-label sale-label"><span>-<?php echo $percent ?>%</span></span>
										<ul class="icon-links">
											<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
												<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview action quick-view" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="pe-7s-search"></em></button></li>
											<?php endif ?>
											<?php if ($this->helper('wishlist')->isAllow() && $helper->isShowWishList()) : ?>
												<li><button class="action action-wishlist" type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="pe-7s-like"></em></button></li>
											<?php endif; ?>
										</ul>
										<?php if($_product->isSaleable()): ?>
											<div class="add-to-cart"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart action" onclick="setLocation('<?php echo $this->helper('checkout/cart')->getAddUrl($_product) ?>')"><span class="icon pe-7s-shopbag"></span><span class="text"><?php echo $this->__('Add to Cart') ?></span></button></div>
										<?php endif; ?>
										<div class="product details product-item-details">
											<div class="time-left margin-bottom10">
												<?php echo $this->getLayout()->createBlock('deals/deals')->setTemplate('mgs/deals/list.phtml')->setProductId($_product->getId())->toHtml(); ?>
											</div>
											<h5 class="product-name">
												<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName(), null, true) ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></a>
											</h5>
											<?php echo $this->getPriceHtml($_product, true) ?>
										</div>
									</div>
								</div>
							</div>
				<?php if($useSlider && $this->getNumberRow() > 1): ?>
					<?php if($i % $countPerSlider == 0 || $i == count($_productCollection)): ?>
						</div>
					<?php endif ?>
				<?php endif ?>
			<?php endforeach ?>
		</div>
		<?php if($useSlider && $this->getNumberRow() == 1): ?>
		</div>
		<?php endif ?>
		<?php if($useSlider): ?>
			<script type="text/javascript">
				mgsjQuery("#deals-product-grid").owlCarousel({
					<?php if ($this->getNumberRow() == 1): ?>
					items : <?php echo $_columnCount ?>,
					<?php else: ?>
					singleItem: true,
					<?php endif ?>
                    rtl: <?php echo Mage::getStoreConfig('mgs_theme/general/right_to_left') ? 'true' : 'false' ?>,
					nav : <?php echo $this->getNavigation() ?>,
					dots : <?php echo $this->getPagination() ?>,
					autoplay: <?php echo $this->getAutoPlay() ?>,
					autoplayHoverPause: <?php echo $this->getStopHover() ?>,
					navText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
					<?php if($this->getNumberRow() == 1): ?>
                        responsive:{
                            0:{
                                items:1
                            },
                            480:{
                                items:2
                            },
                            991:{
                                items:3
                            }
                        }
					<?php endif ?>
				});
			</script>
		<?php endif ?>
	<?php else: ?>
		<div class="alert alert-warning"><span><?php echo $this->__('There are no deals matching the selection.'); ?></span></div>	
	<?php endif ?>
<?php else: ?>
	<div class="alert alert-warning"><span><?php echo $this->__('Please enalbed extension deals first.'); ?></span></div>
<?php endif ?>