<?php $profile = $this->getProfile(); ?>
<div class="detail-profile">
	<div class="row">
		<div class="col-md-3 col-sm-4 col-xs-12">
			<div class="user-wrapper">
				<div class="profile-image">
					<img alt="<?php echo $profile->getName(); ?>" class="img-responsive" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).$profile->getPhoto() ?>">
				</div>
				<div class="desc">
					<h6><?php echo $profile->getName(); ?></h6>
					<p><?php echo $profile->getPosition(); ?></p>
					
				</div>
			</div>
		</div>
		<div class="col-md-9 col-sm-8 col-xs-12">
			<div class="description">
				<h3><?php echo $this->__('Information:')?></h3>
				
				<p><?php echo $profile->getDetail(); ?></p>
				<?php if($profile->getAddress()): ?>
					<p><span class="title"><?php echo $this->__('Address:')?></span><?php echo $profile->getAddress(); ?></p>
				<?php endif; ?>
				<p><span class="title"><?php echo $this->__('Email:')?></span> <?php echo $profile->getEmail(); ?></p>
				
				<div class="social">
				<?php if($profile->getFacebook()): ?>
					<a class="btn-facebook" href="<?php echo $profile->getFacebook(); ?>"><i class="fa fa-facebook"></i></a>
				<?php endif ?>
				<?php if($profile->getGooglePlus()): ?>
					<a class="btn-google" href="<?php echo $profile->getGooglePlus(); ?>"><i class="fa fa-google-plus"></i></a>
				<?php endif ?>
				<?php if($profile->getTwitter()): ?>
					<a class="btn-twitter" href="<?php echo $profile->getTwitter(); ?>"><i class="fa fa-twitter"></i></a>
				<?php endif ?>
				<?php if($profile->getLinkedin()): ?>
					<a class="btn-linkedin" href="<?php echo $profile->getLinkedin(); ?>"><i class="fa fa-linkedin"></i></a>
				<?php endif ?>
				<?php if($profile->getInstagram()): ?>
					<a class="btn-instagram" href="<?php echo $profile->getInstagram(); ?>"><i class="fa fa-instagram"></i></a>
				<?php endif ?>
				</div>
			</div>
		</div>
	</div>
</div>