<?php if ($this->getTitle() != '' || $this->getSubTitle() != ''): ?>
	<div class="content-heading">
		<?php if ($this->getTitle() != ''): ?>
			<h3 class="title"><?php echo $this->getTitle(); ?></h3>
		<?php endif ?>
		<?php if ($this->getSubTitle() != ''): ?>
			<div class="block-note"><?php echo $this->getSubTitle(); ?></div>
		<?php endif ?>
	</div>
<?php endif ?>
<?php $blockId = rand() . time(); ?>
<?php switch ($type = $this->getDisplayType()) {
	case 'new_products':
        $_products = $this->getProductCollection();
		$_idBlock = 'new-products-list-carousel' . $blockId;
    break;
	case 'featured_products':
        $_products = $this->getSpecialProducts('featured');
		$_idBlock = 'featured-products-list-carousel' . $blockId;
    break;
	case 'hot_products':
        $_products = $this->getSpecialProducts('hot');
		$_idBlock = 'hot-products-list-carousel' . $blockId;
    break;
	case 'product_sale':
        $_products = $this->getSaleProducts();
		$_idBlock = 'sale-products-list-carousel' . $blockId;
    break;
	case 'product_rate':
        $_products = $this->getTopRateProducts();
		$_idBlock = 'toprate-products-list-carousel' . $blockId;
    break;
} ?>
<?php $product_url_not_rw = Mage::getBaseUrl() . 'catalog/product/view/id/'; ?>
<div class="block-content">
	<?php if ($_products && count($_products) > 0): ?>
		<?php $panelHelper = $this->helper('mpanel'); ?>
		<?php $size = $panelHelper->convertRatioToMinSize($this->getProductRatio()); ?>
		<?php $useSlider = $this->getSlider(); ?>
		
		<?php $numberCol = $this->getNumberCol(); ?>
		<?php $numberOfCol = $this->getCountPerCol(); ?>
		<?php $onRow = $numberCol * $numberOfCol; ?>
		<?php $col = $panelHelper->getCol($numberCol); ?>
		
		<div class="block <?php echo $type ?>-list list-products-home">
				<?php if($useSlider == 1): ?>
				<div class="owl-carousel" id="<?php echo $_idBlock ?>">
				<?php endif ?>
				
					<?php $i=0; foreach($_products as $_product): $i++; ?>
					
						<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()) ?>
						<?php if($i % $numberOfCol == 1): ?>							
							<div class="list-product-col <?php if(!$useSlider && $numberCol > 1): ?>col-md-<?php echo $col; ?> col-sm-6 col-xs-12<?php endif ?><?php if(!$useSlider && $numberCol == 1): ?> col-xs-12<?php endif ?>">
						<?php endif ?>
								<div class="product-item-info">
									<div class="product-image">
										<a href="<?php echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
											<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive product-image-photo">
										</a>
										<ul class="icon-links">
											<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
												<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview action quick-view" onclick="quickView('<?php echo $product_url_not_rw . $_product->getId() ?>'); return false;"><em class="pe-7s-search"></em></button></li>
											<?php endif ?>
											<?php if ($this->helper('wishlist')->isAllow() && $panelHelper->isShowWishList()) : ?>
												<li><button class="action action-wishlist" type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="pe-7s-like"></em></button></li>
											<?php endif; ?>
											<?php $_compareUrl=$this->getAddToCompareUrl($_product); ?>
											<?php if($_compareUrl && $panelHelper->isShowCompare()): ?>
												<li><button type="button" class="action action-compare" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="pe-7s-graph3"></em></button></li>
											<?php endif; ?>
										</ul>
									</div>

									<div class="product-details product-item-details">
										<h5 class="product-name">
											<a class="product-item-link" href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->stripTags($_product->getName(), null, true) ?></a>
										</h5>
										<?php echo $this->getPriceHtml($_product, true) ?>	
										<?php echo $this->getReviewsSummaryHtml($_product, 'short', "") ?>
										<?php if($panelHelper->isShowAddtoCart() && $_product->isSaleable()): ?>
										<div class="add-to-cart">
											<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn btn-cart action" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span class="text"><?php echo $this->__('Add to Cart'); ?></span></button>
										</div>
									<?php endif ?>
									</div>
								</div>
								
						<?php if($i % $numberOfCol == 0 || $i == count($_products)): ?>
							</div>
						<?php endif ?>
						
						<?php // Clearfix ?>
							<?php if(!$useSlider && ($i % $onRow == 0)): ?>
								<div class="clearfix visible-lg visible-md"></div>
							<?php endif ?>
							
							<?php if(!$useSlider && ($i % (2 * $numberOfCol) == 0)): ?>
								<div class="clearfix visible-sm"></div>
							<?php endif ?>
						<?php // End Clearfix ?>
						
					<?php endforeach ?>
				
				<?php if($useSlider == 1): ?>
				</div>
				<?php endif ?>
			<?php if($useSlider == 1): ?>
				<script type="text/javascript">
					mgsjQuery("#<?php echo $_idBlock ?>").owlCarousel({
						items : <?php echo $numberCol; ?>,
						lazyLoad : false,
						navigation : <?php echo $this->getNavigation() ?>,
						pagination : <?php echo $this->getPagination() ?>,
						autoPlay: <?php echo $this->getAutoPlay() ?>,
						stopOnHover: <?php echo $this->getStopHover() ?>,
						navigationText: ["<i class='fa fa-angle-left'></i>","<i class='fa fa-angle-right'></i>"],
						itemsDesktop: [1199,1],
						itemsDesktopSmall: [991,2],
						itemsTabletSmall: [767,1],
						itemsMobile: [499,1],
						itemsCustom: false
					});
				</script>
			<?php endif ?>
		</div>
	<?php else: ?>
		<div class="alert alert-danger no-product-display">
			<span><?php echo $this->__('There are no products matching the selection.') ?></span>
		</div>
	<?php endif; ?>
</div>