<?php $product_url_not_rw = Mage::getBaseUrl() . 'catalog/product/view/id/'; ?>
<div class="block product-list-block rate-list list-products">
	<div class="block-title">
		<h4 class="title"><?php echo $this->__($this->getTitle()); ?></h4>
	</div>
	<div class="block-content">
		<?php if (($_products = $this->getTopRateProducts()) && (count($_products) > 0)): ?>
			<?php $panelHelper = $this->helper('mpanel'); ?>
			<?php $size = $panelHelper->convertRatioToMinSize(); ?>
			<?php foreach ($_products as $_product): ?>
				<?php $_product = Mage::getModel('catalog/product')->load($_product->getId()) ?>
				<div class="product-item-info">
					<div class="product-image">
						<a class="product-image" href="<?php echo $_product->getProductUrl() ?>">
							<img alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" class="img-responsive" />
						</a>
						<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
							<button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview action quick-view hidden-sm hidden-xs" onclick="quickView('<?php echo $product_url_not_rw . $_product->getId() ?>'); return false;"><em class="pe-7s-search"></em></button>
						<?php endif ?>
					</div>
					<div class="product-item-details">
						<h5 class="product-item-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName(), 'name') ?></a></h5>
						<?php echo $this->getPriceHtml($_product, true) ?>
						<?php echo $this->getReviewsSummaryHtml($_product, 'short','') ?>
					</div>
				</div>
			<?php endforeach ?>
		<?php else: ?>
			<p><?php echo $this->__('There are no products matching the selection.') ?></p>
		<?php endif; ?>
	</div>
</div>