<?php 
	$categories = $this->getCategoryCollection();
	$helper = $this->helper('mpanel');
	$size = $helper->convertRatioToSize($this->getProductRatio());
	if($this->getColumn()){
		$col = $this->getColumn();
	}
	else{
		$col = 3;
	}
	
	$col = $helper->convertColRow($col);
?>
<?php if(count($categories)>0): ?>
	<?php if(count($categories)==1): ?>
		<div class="categories-product-tab">
			<div class="carousel_wrapper">
				<div class="title-content margin-bottom50">
					<h2 class="title">
						<?php if($this->getTitle()!=''): ?>
							<?php echo $this->getTitle() ?>
						<?php else: ?>
							<?php $i=0; foreach($categories as $_category): $i++; ?>
								<?php echo $_category->getName() ?>
							<?php endforeach ?>
						<?php endif ?>
					</h2>
				</div>
			</div>
			<?php $i=0; foreach($categories as $_category): $i++; ?>
				<?php $products = $this->getProductByCategory($_category) ?>
					<?php if(count($products)>0): ?>
						<div class="row">
							<div class="products-grid owl-carousel products-carousel" id="category_products_slider_<?php echo $_category->getId();?>">
								<?php foreach($products as $_product): ?>
								<?php $_product = Mage::getModel('catalog/product')->load($_product->getId());  ?>
								<div class="item">
									<div class="product-content">
										<div class="product-top">
											<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
												<img id="product-collection-image-<?php echo $_product->getId() ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
												<?php if(basename($_product->getData('image')) != basename($_product->getData('small_image'))): ?>
													<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($size['width'], $size['height']) ?>" 
													alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-base"/>
												<?php endif ?>
											</a>
											<?php echo $helper->getProductLabel($_product) ?>
											<ul class="icon-links">
												<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
													<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em></button></li>
												<?php endif ?>
												<?php if ($this->helper('wishlist')->isAllow() && $helper->isShowWishList()) : ?>
													<li><button <?php if($helper->checkInWishilist($_product)): ?> class="on-wishlist"<?php endif ?> type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart-o"></em></button></li>
												<?php endif; ?>
												<?php $_compareUrl=$this->getAddToCompareUrl($_product); ?>
												<?php if($_compareUrl && $helper->isShowCompare()): ?>
													<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
												<?php endif; ?>
											</ul>
										</div>
										<div class="product-desc">
											<div class="cate-name"><?php echo $helper->getCategoryName($_product,$this->getTitle(),$_category); ?></div>
											<h5 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h5>
											<div class="prar<?php if($this->getReviewsSummaryHtml($_product, 'short','') != ''): ?> has-rate<?php endif ?>">
												<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
												<?php echo $this->getReviewsSummaryHtml($_product, 'short',''); ?>
												<?php 
													$_nameAfterChild = $this->getLayout()->getBlock('product_list.swatches');
													$_nameAfterChild->setProduct($_product);
													echo $_nameAfterChild->toHtml();
												?>
											</div>
											<div class="controls">
												<?php if($helper->isShowAddtoCart()): ?>
												<div class="add-to-cart">
														<?php if ($_product->isSaleable()): ?>
															<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span class="icon pe-7s-shopbag"></span><span class="text"><?php echo $this->__('Add to Cart'); ?></span></button>
														<?php else: ?>
															<p><?php echo $this->__('Our of stock') ?></p>
														<?php endif; ?>
													</div>
												<?php endif ?>
											</div>
										</div>
									</div>  
								</div>
								<?php endforeach ?>
							</div>
							<script type="text/javascript">
								initSlider('category_products_slider_<?php echo $_category->getId() ?>', <?php echo $this->getColumn() ?>,false,false,true,false);
							</script>
						</div>
					<?php else: ?>
						<div class="alert alert-danger">
							<p><?php echo $this->__('There are no products matching the selection.') ?></p>
						</div>
					<?php endif ?>
			<?php endforeach ?>
		</div>
	<?php else: ?>
		<div class="categories-product-tab">
			<?php if($this->getTitle()!=''): ?>
				<div class="carousel_wrapper">
					<div class="title-content margin-bottom50">
						<h2 class="title"><?php echo $this->getTitle() ?></h2>
					</div>
				</div>
			<?php endif ?>
			<div class="tabs-container category-product-item">
				<ul class="nav nav-tabs tab-menu" role="tablist">
					<?php $i=0; foreach($categories as $_category): $i++; ?>										
						<li<?php if($i==1): ?> class="active"<?php endif ?> role="presentation">
							<a href="#section-flip-<?php echo $i ?>" role="tab" data-toggle="tab" aria-expanded="true" >
								<span><?php echo $_category->getName() ?></span>
							</a>
						</li>
					<?php endforeach ?>
				</ul>
				<div class="products tab-content">
					<?php $i=0; foreach($categories as $_category): $i++; ?>
						<?php $products = $this->getProductByCategory($_category) ?>
						<div class="tab-pane<?php if($i==1): ?> active<?php endif ?>" id="<?php echo "section-flip-".$i ?>" role="tabpanel">
							<?php if(count($products)>0): ?>
								<div class="row">
									<div class="products-grid owl-carousel products-carousel" id="category_products_slider_<?php echo $_category->getId();?>">
										<?php foreach($products as $_product): ?>
										<?php $_product = Mage::getModel('catalog/product')->load($_product->getId());  ?>
										<div class="item">
											<div class="product-content">
												<div class="product-top">
													<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image">
														<img id="product-collection-image-<?php echo $_product->getId() ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
														<?php if(basename($_product->getData('image')) != basename($_product->getData('small_image'))): ?>
															<img src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize($size['width'], $size['height']) ?>" 
															alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-base"/>
														<?php endif ?>
													</a>
													<?php echo $helper->getProductLabel($_product) ?>
													<ul class="icon-links">
														<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
															<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview quick-view" onclick="quickView('<?php echo $_product->getProductUrl() ?>'); return false;"><em class="fa fa-search"></em></button></li>
														<?php endif ?>
														<?php if ($this->helper('wishlist')->isAllow() && $helper->isShowWishList()) : ?>
															<li><button type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="fa fa-heart-o"></em></button></li>
														<?php endif; ?>
														<?php $_compareUrl=$this->getAddToCompareUrl($_product); ?>
														<?php if($_compareUrl && $helper->isShowCompare()): ?>
															<li><button type="button" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="fa fa-retweet"></em></button></li>
														<?php endif; ?>
													</ul>
												</div>
												<div class="product-desc">
													<h5 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a></h5>
													<div class="prar">
														<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
														<?php echo $this->getReviewsSummaryHtml($_product, 'short',''); ?>
													</div>
													<div class="controls">
														<?php if($helper->isShowAddtoCart()): ?>
															<div class="add-to-cart">
																<?php if ($_product->isSaleable()): ?>
																	<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span class="icon"><i class="fa fa-shopping-cart"></i></span><span class="text"><?php echo $this->__('Add to Cart'); ?></span></button>
																<?php else: ?>
																	<p><?php echo $this->__('Our of stock') ?></p>
																<?php endif; ?>
															</div>
														<?php endif ?>
													</div>
												</div>
											</div>  
										</div>
										<?php endforeach ?>
									</div>
									<script type="text/javascript">
										initSlider('category_products_slider_<?php echo $_category->getId() ?>', <?php echo $this->getColumn() ?>,false,false,true,false);
									</script>
								</div>
							<?php else: ?>
								<div class="alert alert-danger">
									<p><?php echo $this->__('There are no products matching the selection.') ?></p>
								</div>
							<?php endif ?>
						</div>
					<?php endforeach ?>
				</div>
			</div>
		</div>
	<?php endif ?>
<?php else: ?>
	<div class="alert alert-danger">
		<p><?php echo $this->__('There are no categories matching the selection.') ?></p>
	</div>
<?php endif ?>