<?php $_product = $this->getProduct() ?>
<div class="special-product">
    <?php if ($this->getTitle() != ''): ?>
		<div class="content-heading">
			<h3 class="title"><?php echo $this->getTitle(); ?></h3>
		</div>
	<?php endif ?>

    <?php if ($_product->getId()): ?>
        <?php $helper = $this->helper('mpanel') ?>
        <?php $size = $helper->convertRatioToSize($this->getProductRatio()) ?>
		<?php $product_url_not_rw = Mage::getBaseUrl() . 'catalog/product/view/id/'; ?>
		<div class="products-grid">
			<div class="product-item-info item">
				
				<div class="product-content">
				<div class="product-top">
					<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="product-image photo">
						<img id="product-collection-image-<?php echo $_product->getId() ?>" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($size['width'], $size['height']) ?>" alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive"/>
						<?php if(basename($_product->getData('thumbnail')) != basename($_product->getData('small_image'))): ?>
							<img src="<?php echo $this->helper('catalog/image')->init($_product, 'thumbnail')->resize($size['width'], $size['height']) ?>" 
							alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>" class="img-responsive img-hover"/>
						<?php endif ?>
					</a>
					<?php echo $helper->getProductLabel($_product) ?>
					<ul class="icon-links">
						<?php if($this->helper('core')->isModuleEnabled('MGS_QuickView') && Mage::getStoreConfig('quickview/general/active')): ?>
							<li class="li-quickview"><button type="button" title="<?php echo $this->__('Quickview') ?>" class="btn-quickview action quick-view" onclick="quickView('<?php echo $product_url_not_rw . $_product->getId() ?>'); return false;"><em class="pe-7s-search"></em></button></li>
						<?php endif ?>
						<?php if ($this->helper('wishlist')->isAllow() && $helper->isShowWishList()) : ?>
							<li><button class="action action-wishlist" type="button" title="<?php echo $this->__('Add to Wishlist') ?>" onclick="setLocation('<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>')"><em class="pe-7s-like"></em></button></li>
						<?php endif; ?>
						<?php $_compareUrl=$this->getAddToCompareUrl($_product); ?>
						<?php if($_compareUrl && $helper->isShowCompare()): ?>
							<li><button type="button" class="action action-compare" title="<?php echo $this->__('Add to Compare') ?>" onclick="setLocation('<?php echo $_compareUrl ?>')"><em class="pe-7s-graph3"></em></button></li>
						<?php endif; ?>
					</ul>
					<?php if($helper->isShowAddtoCart() && $_product->isSaleable()): ?>
						<div class="add-to-cart">
							<button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="btn-cart action" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span class="icon pe-7s-shopbag"></span><span class="text"><?php echo $this->__('Add to Cart'); ?></span></button>
						</div>
					<?php endif ?>
				</div>
				<?php if ($this->getShowName() || $this->getShowPrice()): ?>
				<div class="product-desc">
					<?php if($this->getShowName()): ?>
					<h5 class="product-name">
						<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($_product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($_product, $_product->getName() , 'name') ?></a>
					</h5>
					<?php endif;?>
					<?php if($this->getShowPrice()):?>
					<?php echo $this->getPriceHtml($_product, true, '-widget-new-grid') ?>
					<?php endif;?>
					<?php 
						$_nameAfterChild = $this->getLayout()->getBlock('product_list.swatches');
						$_nameAfterChild->setProduct($_product);
						echo $_nameAfterChild->toHtml();
					?>
				</div>
				<?php endif;?>
			</div>
			</div>
		</div>
	<?php else: ?>
		<div class="alert alert-danger">
			<span><?php echo $this->__('There are no products matching the selection.') ?></span>
		</div>
    <?php endif ?>
</div>
